# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/chatgpt-webapp',
                'doc_host': 'https://danxu.github.io',
                'git_url': 'https://github.com/danxu/chatgpt-webapp',
                'lib_path': 'chatgpt_webapp'},
  'syms': { 'chatgpt_webapp.chatGPT_webapp': { 'chatgpt_webapp.chatGPT_webapp.app': ( 'chatgpt_webapp.html#app',
                                                                                      'chatgpt_webapp/chatGPT_webapp.py'),
                                               'chatgpt_webapp.chatGPT_webapp.generate_response': ( 'chatgpt_webapp.html#generate_response',
                                                                                                    'chatgpt_webapp/chatGPT_webapp.py')},
            'chatgpt_webapp.core': {'chatgpt_webapp.core.foo': ('core.html#foo', 'chatgpt_webapp/core.py')}}}