# Autogenerated by nbdev

d = { 'settings': { 'branch': 'master',
                'doc_baseurl': '/chatgpt-webapp',
                'doc_host': 'https://biomarker.github.io',
                'git_url': 'https://github.com/biomarker/chatgpt-webapp',
                'lib_path': 'chatgpt_webapp'},
  'syms': {'chatgpt_webapp.core': {'chatgpt_webapp.core.foo': ('core.html#foo', 'chatgpt_webapp/core.py')}}}